---
type: showroom

# Set the left column width to 30%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

tabs:
- name: OpenShift Console
  url: 'https://console-openshift-console.${DOMAIN}'
- name: Migration Toolkit
  url: 'https://mta-mta-${USER}.${DOMAIN}'
- name: Gitea
  url: 'https://gitea.${DOMAIN}/${USER}/mcp'
- name: OpenShift Gitops
  url: 'https://openshift-gitops-server-openshift-gitops.${DOMAIN}'
